version: '3.9'

services:
  opbg:
    build: .
    environment:
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - SECRET_KEY=${SECRET_KEY}
    ports:
      - "8000:8000"
